/* ------------------------------------------------------------------ *
 * Paste-ready setup SQL
 *
 * Bundles the migrations and the empty-portfolio rows into one file that
 * can be run in a hosted database's SQL editor. It exists so setting up
 * a deployment needs nothing installed locally — no Node, no clone, no
 * connection string on your machine.
 *
 * It also writes the row Drizzle uses to track applied migrations, so a
 * later `npm run db:migrate` against the same database is a no-op rather
 * than a failed re-run.
 *
 * Generated, never hand-edited: `npm run db:sql`. CI regenerates it and
 * fails on a difference, so it cannot drift from the schema.
 * ------------------------------------------------------------------ */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { DEFAULT_REMINDERS, TEAM } from '../src/lib/data.ts'

const DIR = 'server/db/migrations'
const OUT = 'docs/setup.sql'

interface Entry { idx: number; when: number; tag: string }

/** Postgres string literal; the only values here are ours, but quote anyway. */
const lit = (v: string) => `'${v.replace(/'/g, "''")}'`

const journal = JSON.parse(readFileSync(`${DIR}/meta/_journal.json`, 'utf8')) as { entries: Entry[] }

const parts: string[] = [
  `-- Altier Properties — database setup`,
  `--`,
  `-- Generated by \`npm run db:sql\`. Do not edit by hand.`,
  `--`,
  `-- Run this once against an empty database (Supabase: SQL Editor → New query,`,
  `-- paste, Run). It creates the schema and the two things the app cannot`,
  `-- start without: the reminder settings and the team a property is assigned`,
  `-- to. No properties, clients or charges — you add those in the interface.`,
  `--`,
  `-- Safe to re-run: it stops with a notice if the schema is already there.`,
  ``,
  `DO $$`,
  `BEGIN`,
  `  IF EXISTS (SELECT 1 FROM information_schema.tables`,
  `             WHERE table_schema = 'public' AND table_name = 'properties') THEN`,
  `    RAISE EXCEPTION 'Altier is already set up in this database — nothing to do.';`,
  `  END IF;`,
  `END $$;`,
  ``,
]

for (const entry of journal.entries) {
  const sql = readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')
  parts.push(`-- ---------------------------------------------------------------`)
  parts.push(`-- migration: ${entry.tag}`)
  parts.push(`-- ---------------------------------------------------------------`)
  parts.push(sql.split('--> statement-breakpoint').join('').trim())
  parts.push('')
}

/* Drizzle decides what to apply by comparing timestamps against the newest
   row here, so recording the migrations makes a later db:migrate a no-op. */
parts.push(
  `-- ---------------------------------------------------------------`,
  `-- Record the migrations as applied, so \`npm run db:migrate\``,
  `-- against this database does nothing rather than failing.`,
  `-- ---------------------------------------------------------------`,
  `CREATE SCHEMA IF NOT EXISTS "drizzle";`,
  `CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (`,
  `  id SERIAL PRIMARY KEY,`,
  `  hash text NOT NULL,`,
  `  created_at bigint`,
  `);`,
)
for (const entry of journal.entries) {
  const hash = createHash('sha256').update(readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')).digest('hex')
  parts.push(`INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at) VALUES (${lit(hash)}, ${entry.when});`)
}
parts.push('')

parts.push(
  `-- ---------------------------------------------------------------`,
  `-- The team. A property is assigned to a manager, so at least one`,
  `-- person has to exist before a property can.`,
  `-- ---------------------------------------------------------------`,
)
for (const m of TEAM) {
  parts.push(
    `INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES (`
    + [m.id, m.name, m.role, m.title, m.email, m.phone, m.since].map(lit).join(', ')
    + `);`,
  )
}
parts.push('')

const r = DEFAULT_REMINDERS
parts.push(
  `-- ---------------------------------------------------------------`,
  `-- Reminder settings. One row, always id 1 — the app reads it on`,
  `-- every load and refuses to start without it.`,
  `-- ---------------------------------------------------------------`,
  `INSERT INTO "reminder_settings" (`,
  `  id, rent_due_lead_days, lease_expiry_lead_days, check_in_lead_hours,`,
  `  vacancy_alert_days, maintenance_lead_days, channels,`,
  `  quiet_hours_enabled, quiet_hours_from, quiet_hours_to, digest`,
  `) VALUES (`,
  `  1, ${r.rentDueLeadDays}, ${r.leaseExpiryLeadDays}, ${r.checkInLeadHours},`,
  `  ${r.vacancyAlertDays}, ${r.maintenanceLeadDays}, ${lit(JSON.stringify(r.channels))}::jsonb,`,
  `  ${r.quietHours.enabled}, ${lit(r.quietHours.from)}, ${lit(r.quietHours.to)}, ${lit(r.digest)}`,
  `);`,
  ``,
  `-- Done. Set DATABASE_URL on the host to this database's pooled`,
  `-- connection string, redeploy, and check /api/health.`,
  ``,
)

const out = parts.join('\n')

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8')
  if (current !== out) {
    console.error(`${OUT} is out of date — run \`npm run db:sql\` and commit the result.`)
    process.exit(1)
  }
  console.log(`${OUT} is up to date`)
} else {
  writeFileSync(OUT, out)
  console.log(`wrote ${OUT} (${out.split('\n').length} lines, ${TEAM.length} team members)`)
}
