/* ------------------------------------------------------------------ *
 * Paste-ready setup SQL
 *
 * Bundles the migrations and the empty-portfolio rows into one file that
 * can be run in a hosted database's SQL editor. It exists so setting up
 * a deployment needs nothing installed locally — no Node, no clone, no
 * connection string on your machine.
 *
 * It also writes the row Drizzle uses to track applied migrations, so a
 * later `npm run db:migrate` against the same database is a no-op rather
 * than a failed re-run.
 *
 * Generated, never hand-edited: `npm run db:sql`. CI regenerates it and
 * fails on a difference, so it cannot drift from the schema.
 * ------------------------------------------------------------------ */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { DEFAULT_REMINDERS } from '../src/lib/data.js'

const DIR = 'server/db/migrations'
const OUT = 'docs/setup.sql'
const UPGRADE = 'docs/upgrade.sql'
const EXPECTED = 'server/db/expected-migrations.ts'

interface Entry { idx: number; when: number; tag: string }

/** Postgres string literal; the only values here are ours, but quote anyway. */
const lit = (v: string) => `'${v.replace(/'/g, "''")}'`

const journal = JSON.parse(readFileSync(`${DIR}/meta/_journal.json`, 'utf8')) as { entries: Entry[] }

const parts: string[] = [
  `-- Altier Properties — database setup`,
  `--`,
  `-- Generated by \`npm run db:sql\`. Do not edit by hand.`,
  `--`,
  `-- Run this once against an empty database (Supabase: SQL Editor → New query,`,
  `-- paste, Run). It creates the schema and the one row the app cannot start`,
  `-- without: the reminder settings. No people, no properties, no charges —`,
  `-- the first person to open the app creates the owner account, and the`,
  `-- portfolio is filled in from there.`,
  `--`,
  `-- Safe to re-run: it stops with a notice if the schema is already there.`,
  ``,
  `DO $$`,
  `BEGIN`,
  `  IF EXISTS (SELECT 1 FROM information_schema.tables`,
  `             WHERE table_schema = 'public' AND table_name = 'properties') THEN`,
  `    RAISE EXCEPTION 'Altier is already set up in this database — nothing to do.';`,
  `  END IF;`,
  `END $$;`,
  ``,
]

for (const entry of journal.entries) {
  const sql = readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')
  parts.push(`-- ---------------------------------------------------------------`)
  parts.push(`-- migration: ${entry.tag}`)
  parts.push(`-- ---------------------------------------------------------------`)
  parts.push(sql.split('--> statement-breakpoint').join('').trim())
  parts.push('')
}

/* Drizzle decides what to apply by comparing timestamps against the newest
   row here, so recording the migrations makes a later db:migrate a no-op. */
parts.push(
  `-- ---------------------------------------------------------------`,
  `-- Record the migrations as applied, so \`npm run db:migrate\``,
  `-- against this database does nothing rather than failing.`,
  `-- ---------------------------------------------------------------`,
  `CREATE SCHEMA IF NOT EXISTS "drizzle";`,
  `CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (`,
  `  id SERIAL PRIMARY KEY,`,
  `  hash text NOT NULL,`,
  `  created_at bigint`,
  `);`,
)
for (const entry of journal.entries) {
  const hash = createHash('sha256').update(readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')).digest('hex')
  parts.push(`INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at) VALUES (${lit(hash)}, ${entry.when});`)
}
parts.push('')

const r = DEFAULT_REMINDERS
parts.push(
  `-- ---------------------------------------------------------------`,
  `-- Reminder settings. One row, always id 1 — the app reads it on`,
  `-- every load and refuses to start without it.`,
  `-- ---------------------------------------------------------------`,
  `INSERT INTO "reminder_settings" (`,
  `  id, rent_due_lead_days, lease_expiry_lead_days, check_in_lead_hours,`,
  `  vacancy_alert_days, maintenance_lead_days, channels,`,
  `  quiet_hours_enabled, quiet_hours_from, quiet_hours_to, digest`,
  `) VALUES (`,
  `  1, ${r.rentDueLeadDays}, ${r.leaseExpiryLeadDays}, ${r.checkInLeadHours},`,
  `  ${r.vacancyAlertDays}, ${r.maintenanceLeadDays}, ${lit(JSON.stringify(r.channels))}::jsonb,`,
  `  ${r.quietHours.enabled}, ${lit(r.quietHours.from)}, ${lit(r.quietHours.to)}, ${lit(r.digest)}`,
  `);`,
  ``,
  `-- Done. Set DATABASE_URL on the host to this database's pooled`,
  `-- connection string, redeploy, and check /api/health. Then open the app`,
  `-- and create the owner account before sharing the address.`,
  ``,
)

const out = parts.join('\n')

/* ------------------------------------------------------------------ *
 * What the code expects to be applied
 *
 * The deployed API cannot read the migrations folder — it is not
 * bundled into a serverless function — so the hashes are compiled in.
 * /api/health compares them against the migration log and can then say
 * "this database is two migrations behind" instead of failing later on
 * a column that is not there yet.
 * ------------------------------------------------------------------ */

const expected = [
  `/* Generated by \`npm run db:sql\`. Do not edit by hand. */`,
  ``,
  `/** Every migration this build of the code expects to have been applied. */`,
  `export const EXPECTED_MIGRATIONS: ReadonlyArray<{ tag: string; hash: string }> = [`,
  ...journal.entries.map((entry) => {
    const hash = createHash('sha256').update(readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')).digest('hex')
    return `  { tag: '${entry.tag}', hash: '${hash}' },`
  }),
  `]`,
  ``,
].join('\n')

/* ------------------------------------------------------------------ *
 * The upgrade file
 *
 * setup.sql builds a database from nothing. A database that already
 * exists needs the migrations it has not seen yet, and only those — so
 * this emits every migration after the first, each skipped if its
 * bookkeeping row is already there. Running it twice does nothing.
 * ------------------------------------------------------------------ */

const upgrade: string[] = [
  `-- Altier Properties — upgrade an existing database`,
  `--`,
  `-- Generated by \`npm run db:sql\`. Do not edit by hand.`,
  `--`,
  `-- Run this against a database that was set up with an earlier version`,
  `-- of docs/setup.sql. It applies only the migrations that database has`,
  `-- not seen, and is safe to run more than once — each block checks the`,
  `-- migration log first and skips itself if it has already been applied.`,
  `--`,
  `-- On a database that is already current it does nothing and says so.`,
  ``,
  `CREATE SCHEMA IF NOT EXISTS "drizzle";`,
  `CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (`,
  `  id SERIAL PRIMARY KEY,`,
  `  hash text NOT NULL,`,
  `  created_at bigint`,
  `);`,
  ``,
]

const later = journal.entries.slice(1)
for (const entry of later) {
  const body = readFileSync(`${DIR}/${entry.tag}.sql`, 'utf8')
  const hash = createHash('sha256').update(body).digest('hex')
  /* Dollar-quoted so the migration's own quotes need no escaping, and
     tagged uniquely in case a migration ever contains $$ itself. */
  const tag = `mig_${entry.idx}`
  upgrade.push(
    `-- ---------------------------------------------------------------`,
    `-- migration: ${entry.tag}`,
    `-- ---------------------------------------------------------------`,
    `DO $${tag}$`,
    `BEGIN`,
    `  IF EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE hash = ${lit(hash)}) THEN`,
    `    RAISE NOTICE 'already applied: ${entry.tag}';`,
    `  ELSE`,
    `    EXECUTE $${tag}_sql$`,
    body.split('--> statement-breakpoint').join('').trim(),
    `    $${tag}_sql$;`,
    `    INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at)`,
    `    VALUES (${lit(hash)}, ${entry.when});`,
    `    RAISE NOTICE 'applied: ${entry.tag}';`,
    `  END IF;`,
    `END $${tag}$;`,
    ``,
  )
}
upgrade.push(
  `-- Done. Redeploy so the app picks up the code that uses this schema.`,
  ``,
)
const upgradeOut = upgrade.join('\n')

if (process.argv.includes('--check')) {
  let stale = false
  for (const [file, want] of [[OUT, out], [UPGRADE, upgradeOut], [EXPECTED, expected]] as const) {
    if (readFileSync(file, 'utf8') !== want) {
      console.error(`${file} is out of date — run \`npm run db:sql\` and commit the result.`)
      stale = true
    }
  }
  if (stale) process.exit(1)
  console.log(`${OUT}, ${UPGRADE} and ${EXPECTED} are up to date`)
} else {
  writeFileSync(OUT, out)
  writeFileSync(UPGRADE, upgradeOut)
  writeFileSync(EXPECTED, expected)
  console.log(`wrote ${OUT} (${out.split('\n').length} lines)`)
  console.log(`wrote ${UPGRADE} (${later.length} migration${later.length === 1 ? '' : 's'} beyond the first)`)
  console.log(`wrote ${EXPECTED} (${journal.entries.length} expected)`)
}
