/* Generated by `npm run db:sql`. Do not edit by hand. */

/** Every migration this build of the code expects to have been applied. */
export const EXPECTED_MIGRATIONS: ReadonlyArray<{ tag: string; hash: string }> = [
  { tag: '0000_init', hash: '0d6cd2f3cc444ee70ee412a9698e0300b24221be711b35db0195d24bc3dda3ee' },
  { tag: '0001_auth', hash: 'fd0a043c8b2d7cb874e435d8b42745232e9a3c7ccc7cdbaa38503b2dfb5fb38f' },
  { tag: '0002_oauth', hash: '7995837e230ff8c1a909c8683ab738da26d778c999fedfc08aed767d9f15f827' },
]
