-- Altier Properties — database setup
--
-- Generated by `npm run db:sql`. Do not edit by hand.
--
-- Run this once against an empty database (Supabase: SQL Editor → New query,
-- paste, Run). It creates the schema and the two things the app cannot
-- start without: the reminder settings and the team a property is assigned
-- to. No properties, clients or charges — you add those in the interface.
--
-- Safe to re-run: it stops with a notice if the schema is already there.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_schema = 'public' AND table_name = 'properties') THEN
    RAISE EXCEPTION 'Altier is already set up in this database — nothing to do.';
  END IF;
END $$;

-- ---------------------------------------------------------------
-- migration: 0000_init
-- ---------------------------------------------------------------
CREATE TYPE "public"."booking_source" AS ENUM('direct', 'airbnb', 'booking_com', 'agency', 'corporate');
CREATE TYPE "public"."booking_status" AS ENUM('upcoming', 'in_progress', 'completed', 'cancelled', 'pending');
CREATE TYPE "public"."charge_type" AS ENUM('rent', 'advance', 'booking', 'deposit', 'utilities', 'service_fee', 'late_fee', 'maintenance_recharge');
CREATE TYPE "public"."client_kind" AS ENUM('tenant', 'guest', 'corporate', 'owner');
CREATE TYPE "public"."client_status" AS ENUM('active', 'past', 'prospect');
CREATE TYPE "public"."comm_channel" AS ENUM('email', 'call', 'sms', 'note', 'portal');
CREATE TYPE "public"."comm_direction" AS ENUM('inbound', 'outbound');
CREATE TYPE "public"."document_category" AS ENUM('lease', 'title', 'insurance', 'inspection', 'compliance', 'invoice', 'id');
CREATE TYPE "public"."invoice_status" AS ENUM('paid', 'pending', 'overdue', 'upcoming', 'partial');
CREATE TYPE "public"."maintenance_category" AS ENUM('plumbing', 'electrical', 'hvac', 'appliance', 'structural', 'cleaning', 'safety', 'grounds');
CREATE TYPE "public"."maintenance_priority" AS ENUM('urgent', 'high', 'medium', 'low');
CREATE TYPE "public"."maintenance_status" AS ENUM('reported', 'scheduled', 'in_progress', 'awaiting_parts', 'completed');
CREATE TYPE "public"."payment_method" AS ENUM('bank_transfer', 'card', 'mobile_money', 'cash');
CREATE TYPE "public"."property_status" AS ENUM('available', 'occupied', 'reserved', 'maintenance', 'inactive');
CREATE TYPE "public"."property_type" AS ENUM('apartment', 'house', 'villa', 'serviced', 'short_stay', 'commercial');
CREATE TYPE "public"."role" AS ENUM('owner', 'manager', 'staff', 'accountant');
CREATE TYPE "public"."tenancy_mode" AS ENUM('long_term', 'rental', 'short_stay');
CREATE TABLE "bookings" (
	"id" text PRIMARY KEY NOT NULL,
	"reference" text NOT NULL,
	"property_id" text NOT NULL,
	"client_id" text NOT NULL,
	"mode" "tenancy_mode" NOT NULL,
	"status" "booking_status" NOT NULL,
	"starts_on" date NOT NULL,
	"ends_on" date,
	"rate" bigint NOT NULL,
	"deposit" bigint NOT NULL,
	"advance_months" integer DEFAULT 0 NOT NULL,
	"paid_through" date,
	"notice_days" integer DEFAULT 0 NOT NULL,
	"guests" integer NOT NULL,
	"source" "booking_source" NOT NULL,
	"check_in" time NOT NULL,
	"check_out" time NOT NULL,
	"notes" text NOT NULL,
	"created_at" date NOT NULL,
	CONSTRAINT "bookings_reference_unique" UNIQUE("reference"),
	CONSTRAINT "bookings_range_valid" CHECK ("bookings"."ends_on" IS NULL OR "bookings"."ends_on" > "bookings"."starts_on"),
	CONSTRAINT "bookings_open_ended_is_rental" CHECK ("bookings"."ends_on" IS NOT NULL OR "bookings"."mode" = 'rental')
);

CREATE TABLE "client_documents" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" text NOT NULL,
	"name" text NOT NULL,
	"category" "document_category" NOT NULL,
	"size_kb" integer NOT NULL,
	"uploaded_at" date NOT NULL,
	"uploaded_by" text NOT NULL
);

CREATE TABLE "client_properties" (
	"client_id" text NOT NULL,
	"property_id" text NOT NULL,
	CONSTRAINT "client_properties_client_id_property_id_pk" PRIMARY KEY("client_id","property_id")
);

CREATE TABLE "clients" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"kind" "client_kind" NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"nationality" text NOT NULL,
	"since" date NOT NULL,
	"status" "client_status" NOT NULL,
	"notes" text NOT NULL,
	"emergency_contact" text NOT NULL,
	"lifetime_value" bigint NOT NULL,
	"rating" real NOT NULL
);

CREATE TABLE "communications" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" text NOT NULL,
	"channel" "comm_channel" NOT NULL,
	"direction" "comm_direction" NOT NULL,
	"subject" text NOT NULL,
	"preview" text NOT NULL,
	"at" date NOT NULL,
	"author" text NOT NULL
);

CREATE TABLE "invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"number" text NOT NULL,
	"property_id" text NOT NULL,
	"client_id" text NOT NULL,
	"booking_id" text,
	"type" charge_type NOT NULL,
	"issued_on" date NOT NULL,
	"due_on" date NOT NULL,
	"amount" bigint NOT NULL,
	"earns_from" date NOT NULL,
	"earns_to" date NOT NULL,
	"paid_amount" bigint DEFAULT 0 NOT NULL,
	"status" "invoice_status" NOT NULL,
	"method" "payment_method",
	"paid_on" date,
	"memo" text NOT NULL,
	CONSTRAINT "invoices_number_unique" UNIQUE("number"),
	CONSTRAINT "invoices_earns_valid" CHECK ("invoices"."earns_to" > "invoices"."earns_from"),
	CONSTRAINT "invoices_amount_positive" CHECK ("invoices"."amount" >= 0),
	CONSTRAINT "invoices_paid_within_amount" CHECK ("invoices"."paid_amount" >= 0 AND "invoices"."paid_amount" <= "invoices"."amount"),
	CONSTRAINT "invoices_paid_consistent" CHECK (("invoices"."paid_on" IS NULL) = ("invoices"."paid_amount" = 0))
);

CREATE TABLE "maintenance_events" (
	"id" text PRIMARY KEY NOT NULL,
	"request_id" text NOT NULL,
	"position" integer NOT NULL,
	"at" date NOT NULL,
	"label" text NOT NULL,
	"by" text NOT NULL
);

CREATE TABLE "maintenance_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"reference" text NOT NULL,
	"property_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"category" "maintenance_category" NOT NULL,
	"priority" "maintenance_priority" NOT NULL,
	"status" "maintenance_status" NOT NULL,
	"vendor" text NOT NULL,
	"trade" text NOT NULL,
	"assignee_id" text NOT NULL,
	"reported_by" text NOT NULL,
	"reported_on" date NOT NULL,
	"due_on" date NOT NULL,
	"completed_on" date,
	"estimated_cost" bigint NOT NULL,
	"actual_cost" bigint,
	CONSTRAINT "maintenance_requests_reference_unique" UNIQUE("reference"),
	CONSTRAINT "maintenance_completed_consistent" CHECK (("maintenance_requests"."status" = 'completed') = ("maintenance_requests"."completed_on" IS NOT NULL))
);

CREATE TABLE "occupancy_spells" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"client_name" text NOT NULL,
	"starts_on" date NOT NULL,
	"ends_on" date,
	"mode" "tenancy_mode" NOT NULL,
	"revenue" bigint NOT NULL
);

CREATE TABLE "properties" (
	"id" text PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"type" "property_type" NOT NULL,
	"mode" "tenancy_mode" NOT NULL,
	"status" "property_status" NOT NULL,
	"address_line1" text NOT NULL,
	"district" text NOT NULL,
	"city" text NOT NULL,
	"country" text NOT NULL,
	"map_x" real NOT NULL,
	"map_y" real NOT NULL,
	"bedrooms" integer NOT NULL,
	"bathrooms" integer NOT NULL,
	"size_sqm" integer NOT NULL,
	"price" bigint NOT NULL,
	"manager_id" text NOT NULL,
	"rating" real NOT NULL,
	"available_from" date,
	"acquired_on" date NOT NULL,
	"yield_pct" real NOT NULL,
	"notes" text NOT NULL,
	"photo_seed" integer NOT NULL,
	CONSTRAINT "properties_code_unique" UNIQUE("code"),
	CONSTRAINT "properties_price_positive" CHECK ("properties"."price" >= 0),
	CONSTRAINT "properties_rating_range" CHECK ("properties"."rating" >= 0 AND "properties"."rating" <= 5)
);

CREATE TABLE "property_amenities" (
	"property_id" text NOT NULL,
	"amenity" text NOT NULL,
	CONSTRAINT "property_amenities_property_id_amenity_pk" PRIMARY KEY("property_id","amenity")
);

CREATE TABLE "property_documents" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"name" text NOT NULL,
	"category" "document_category" NOT NULL,
	"size_kb" integer NOT NULL,
	"uploaded_at" date NOT NULL,
	"uploaded_by" text NOT NULL
);

CREATE TABLE "property_maintenance_notes" (
	"id" text PRIMARY KEY NOT NULL,
	"property_id" text NOT NULL,
	"position" integer NOT NULL,
	"note" text NOT NULL
);

CREATE TABLE "reminder_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"rent_due_lead_days" integer NOT NULL,
	"lease_expiry_lead_days" integer NOT NULL,
	"check_in_lead_hours" integer NOT NULL,
	"vacancy_alert_days" integer NOT NULL,
	"maintenance_lead_days" integer NOT NULL,
	"channels" jsonb NOT NULL,
	"quiet_hours_enabled" boolean NOT NULL,
	"quiet_hours_from" time NOT NULL,
	"quiet_hours_to" time NOT NULL,
	"digest" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reminder_settings_single_row" CHECK ("reminder_settings"."id" = 1)
);

CREATE TABLE "team_members" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"role" "role" NOT NULL,
	"title" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"since" date NOT NULL,
	CONSTRAINT "team_members_email_unique" UNIQUE("email")
);

ALTER TABLE "bookings" ADD CONSTRAINT "bookings_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "client_properties" ADD CONSTRAINT "client_properties_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "client_properties" ADD CONSTRAINT "client_properties_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "communications" ADD CONSTRAINT "communications_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_booking_id_bookings_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "maintenance_events" ADD CONSTRAINT "maintenance_events_request_id_maintenance_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."maintenance_requests"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "maintenance_requests" ADD CONSTRAINT "maintenance_requests_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "maintenance_requests" ADD CONSTRAINT "maintenance_requests_assignee_id_team_members_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "occupancy_spells" ADD CONSTRAINT "occupancy_spells_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "properties" ADD CONSTRAINT "properties_manager_id_team_members_id_fk" FOREIGN KEY ("manager_id") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "property_amenities" ADD CONSTRAINT "property_amenities_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "property_documents" ADD CONSTRAINT "property_documents_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "property_maintenance_notes" ADD CONSTRAINT "property_maintenance_notes_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "bookings_property_idx" ON "bookings" USING btree ("property_id");
CREATE INDEX "bookings_client_idx" ON "bookings" USING btree ("client_id");
CREATE INDEX "bookings_status_idx" ON "bookings" USING btree ("status");
CREATE INDEX "bookings_range_idx" ON "bookings" USING btree ("starts_on","ends_on");
CREATE INDEX "client_documents_client_idx" ON "client_documents" USING btree ("client_id");
CREATE INDEX "clients_status_idx" ON "clients" USING btree ("status");
CREATE INDEX "clients_kind_idx" ON "clients" USING btree ("kind");
CREATE INDEX "communications_client_at_idx" ON "communications" USING btree ("client_id","at");
CREATE INDEX "invoices_property_idx" ON "invoices" USING btree ("property_id");
CREATE INDEX "invoices_client_idx" ON "invoices" USING btree ("client_id");
CREATE INDEX "invoices_status_idx" ON "invoices" USING btree ("status");
CREATE INDEX "invoices_due_idx" ON "invoices" USING btree ("due_on");
CREATE INDEX "invoices_paid_on_idx" ON "invoices" USING btree ("paid_on");
CREATE INDEX "invoices_earns_idx" ON "invoices" USING btree ("earns_from","earns_to");
CREATE UNIQUE INDEX "maintenance_events_order_idx" ON "maintenance_events" USING btree ("request_id","position");
CREATE INDEX "maintenance_property_idx" ON "maintenance_requests" USING btree ("property_id");
CREATE INDEX "maintenance_status_idx" ON "maintenance_requests" USING btree ("status");
CREATE INDEX "maintenance_due_idx" ON "maintenance_requests" USING btree ("due_on");
CREATE INDEX "occupancy_property_idx" ON "occupancy_spells" USING btree ("property_id");
CREATE INDEX "properties_status_idx" ON "properties" USING btree ("status");
CREATE INDEX "properties_mode_idx" ON "properties" USING btree ("mode");
CREATE INDEX "properties_manager_idx" ON "properties" USING btree ("manager_id");
CREATE INDEX "property_documents_property_idx" ON "property_documents" USING btree ("property_id");
CREATE UNIQUE INDEX "property_notes_order_idx" ON "property_maintenance_notes" USING btree ("property_id","position");

-- ---------------------------------------------------------------
-- migration: 0001_auth
-- ---------------------------------------------------------------
CREATE TABLE "sessions" (
	"token_hash" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"user_agent" text
);

ALTER TABLE "team_members" ADD COLUMN "password_hash" text;
ALTER TABLE "team_members" ADD COLUMN "password_set_at" timestamp with time zone;
ALTER TABLE "team_members" ADD COLUMN "failed_attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "team_members" ADD COLUMN "locked_until" timestamp with time zone;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_member_id_team_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "sessions_member_idx" ON "sessions" USING btree ("member_id");
CREATE INDEX "sessions_expiry_idx" ON "sessions" USING btree ("expires_at");
CREATE INDEX "team_members_email_idx" ON "team_members" USING btree ("email");

-- ---------------------------------------------------------------
-- migration: 0002_oauth
-- ---------------------------------------------------------------
CREATE TYPE "public"."auth_provider" AS ENUM('google', 'apple');
CREATE TABLE "identities" (
	"provider" "auth_provider" NOT NULL,
	"subject" text NOT NULL,
	"member_id" text NOT NULL,
	"email" text,
	"linked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone,
	CONSTRAINT "identities_provider_subject_pk" PRIMARY KEY("provider","subject")
);

CREATE TABLE "oauth_states" (
	"state_hash" text PRIMARY KEY NOT NULL,
	"provider" "auth_provider" NOT NULL,
	"verifier" text,
	"nonce" text NOT NULL,
	"browser_hash" text NOT NULL,
	"redirect_uri" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);

ALTER TABLE "identities" ADD CONSTRAINT "identities_member_id_team_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "identities_member_idx" ON "identities" USING btree ("member_id");
CREATE INDEX "oauth_states_expiry_idx" ON "oauth_states" USING btree ("expires_at");

-- ---------------------------------------------------------------
-- Record the migrations as applied, so `npm run db:migrate`
-- against this database does nothing rather than failing.
-- ---------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);
INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at) VALUES ('0d6cd2f3cc444ee70ee412a9698e0300b24221be711b35db0195d24bc3dda3ee', 1787742595460);
INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at) VALUES ('fd0a043c8b2d7cb874e435d8b42745232e9a3c7ccc7cdbaa38503b2dfb5fb38f', 1787776478682);
INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at) VALUES ('7995837e230ff8c1a909c8683ab738da26d778c999fedfc08aed767d9f15f827', 1787810234659);

-- ---------------------------------------------------------------
-- The team. A property is assigned to a manager, so at least one
-- person has to exist before a property can.
-- ---------------------------------------------------------------
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-01', 'Nakato Ssemakula', 'owner', 'Founder & Principal', 'nakato.ssemakula@altier.co.ug', '+256 772 400 118', '2018-03-01');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-02', 'Brian Kizito', 'manager', 'Head of Portfolio', 'brian.kizito@altier.co.ug', '+256 772 776 240', '2019-06-14');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-03', 'Aisha Namutebi', 'manager', 'Short-Stay Manager', 'aisha.namutebi@altier.co.ug', '+256 701 550 907', '2021-01-11');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-04', 'Tendo Wasswa', 'manager', 'Commercial Lettings', 'tendo.wasswa@altier.co.ug', '+256 752 228 601', '2020-09-02');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-05', 'Sarah Nabbosa', 'accountant', 'Financial Controller', 'sarah.nabbosa@altier.co.ug', '+256 772 331 776', '2019-11-25');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-06', 'Ronald Okello', 'staff', 'Operations & Turnover', 'ronald.okello@altier.co.ug', '+256 701 118 442', '2022-04-19');
INSERT INTO "team_members" (id, name, role, title, email, phone, since) VALUES ('tm-07', 'Patience Akello', 'staff', 'Guest Experience', 'patience.akello@altier.co.ug', '+256 752 640 315', '2023-02-06');

-- ---------------------------------------------------------------
-- Reminder settings. One row, always id 1 — the app reads it on
-- every load and refuses to start without it.
-- ---------------------------------------------------------------
INSERT INTO "reminder_settings" (
  id, rent_due_lead_days, lease_expiry_lead_days, check_in_lead_hours,
  vacancy_alert_days, maintenance_lead_days, channels,
  quiet_hours_enabled, quiet_hours_from, quiet_hours_to, digest
) VALUES (
  1, 5, 60, 24,
  14, 3, '{"inApp":true,"email":true,"sms":false,"push":true}'::jsonb,
  true, '21:00', '07:30', 'daily'
);

-- Done. Set DATABASE_URL on the host to this database's pooled
-- connection string, redeploy, and check /api/health.
