-- Altier Properties — upgrade an existing database
--
-- Generated by `npm run db:sql`. Do not edit by hand.
--
-- Run this against a database that was set up with an earlier version
-- of docs/setup.sql. It applies only the migrations that database has
-- not seen, and is safe to run more than once — each block checks the
-- migration log first and skips itself if it has already been applied.
--
-- On a database that is already current it does nothing and says so.

CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);

-- ---------------------------------------------------------------
-- migration: 0001_auth
-- ---------------------------------------------------------------
DO $mig_1$
BEGIN
  IF EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE hash = 'fd0a043c8b2d7cb874e435d8b42745232e9a3c7ccc7cdbaa38503b2dfb5fb38f') THEN
    RAISE NOTICE 'already applied: 0001_auth';
  ELSE
    EXECUTE $mig_1_sql$
CREATE TABLE "sessions" (
	"token_hash" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"user_agent" text
);

ALTER TABLE "team_members" ADD COLUMN "password_hash" text;
ALTER TABLE "team_members" ADD COLUMN "password_set_at" timestamp with time zone;
ALTER TABLE "team_members" ADD COLUMN "failed_attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "team_members" ADD COLUMN "locked_until" timestamp with time zone;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_member_id_team_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "sessions_member_idx" ON "sessions" USING btree ("member_id");
CREATE INDEX "sessions_expiry_idx" ON "sessions" USING btree ("expires_at");
CREATE INDEX "team_members_email_idx" ON "team_members" USING btree ("email");
    $mig_1_sql$;
    INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at)
    VALUES ('fd0a043c8b2d7cb874e435d8b42745232e9a3c7ccc7cdbaa38503b2dfb5fb38f', 1787776478682);
    RAISE NOTICE 'applied: 0001_auth';
  END IF;
END $mig_1$;

-- ---------------------------------------------------------------
-- migration: 0002_oauth
-- ---------------------------------------------------------------
DO $mig_2$
BEGIN
  IF EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE hash = '7995837e230ff8c1a909c8683ab738da26d778c999fedfc08aed767d9f15f827') THEN
    RAISE NOTICE 'already applied: 0002_oauth';
  ELSE
    EXECUTE $mig_2_sql$
CREATE TYPE "public"."auth_provider" AS ENUM('google', 'apple');
CREATE TABLE "identities" (
	"provider" "auth_provider" NOT NULL,
	"subject" text NOT NULL,
	"member_id" text NOT NULL,
	"email" text,
	"linked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone,
	CONSTRAINT "identities_provider_subject_pk" PRIMARY KEY("provider","subject")
);

CREATE TABLE "oauth_states" (
	"state_hash" text PRIMARY KEY NOT NULL,
	"provider" "auth_provider" NOT NULL,
	"verifier" text,
	"nonce" text NOT NULL,
	"browser_hash" text NOT NULL,
	"redirect_uri" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);

ALTER TABLE "identities" ADD CONSTRAINT "identities_member_id_team_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "identities_member_idx" ON "identities" USING btree ("member_id");
CREATE INDEX "oauth_states_expiry_idx" ON "oauth_states" USING btree ("expires_at");
    $mig_2_sql$;
    INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at)
    VALUES ('7995837e230ff8c1a909c8683ab738da26d778c999fedfc08aed767d9f15f827', 1787810234659);
    RAISE NOTICE 'applied: 0002_oauth';
  END IF;
END $mig_2$;

-- Done. Redeploy so the app picks up the code that uses this schema.
